GET http://localhost:4001/api/v1/users

###

POST http://localhost:4001/api/v1/users
Content-Type: application/json

{
    "username": "bank4",
    "email": "bank4@gmail.com"
}


### ทดสอบ PUT 
PUT http://localhost:4001/api/v1/users/1
Content-Type: application/json

{
    "username": "bank_updated",
    "email": "bank_new@gmail.com",
    "password": "mypassword123"
}



### ทดสอบ DELETE 
DELETE http://localhost:4001/api/v1/users/1