GET http://localhost:4001/api/v2/users

###

POST http://localhost:4001/api/v2/users
Content-Type: application/json

{
    "username": "bank1234",
    "email": "bank_new1234@gmail.com",
    "password": "mypassword1234"
}


### ทดสอบ PUT 
PUT http://localhost:4001/api/v2/users/6a0be6e4821e94feb72d4b2c
Content-Type: application/json

{
    "username": "bank12345",
    "email": "bank_new12345@gmail.com",
    "password": "mypassword12345"
}



### ทดสอบ DELETE 
DELETE http://localhost:4001/api/v2/users/6a0be6e4821e94feb72d4b2c